spring:
   datasource:
      username: videogamedb
      password: videogamedb
      url: jdbc:mysql://localhost:3306/videogamedb
      
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
      
   sql:
      init:
         mode: always
         